import {
    BeigeSofa,
    blackChair,
    pendant,
    chair,
    chair2,
    chairs,
    cup,
    grayChair,
    lamp,
    lamp1,
    silky,
    sofa,
    tableSet,
    vase,
    whiteLight,
    whiteMug,
    yellowChair,
    table,
  } from "../assets";
  
  export const ceremics = [
    {
      id: 1,
      icon: chair,
      name: "The Dandy chair",
      price: "4000",
    },
    {
      id: 2,
      icon: vase,
      name: "Rustic Vase Set",
      price: "2200",
    },
    {
      id: 3,
      icon: silky,
      name: "The Silky Vase",
      price: "2500",
    },
    {
      id: 4,
      icon: lamp,
      name: "The Lucy Lamp",
      price: "3400",
    },
  ];
  
  export const popular = [
    {
      id: 5,
      icon1: sofa,
      name: "The Poplar suede sofa",
      price: "10400",
    },
    {
      id: 6,
      icon: chair2,
      name: "The Dandy chair",
      price: "5400",
    },
    {
      id: 7,
      icon: lamp1,
      name: "The Lucy Lamp",
      price: "3400",
    },
  ];
  
  export const AllProducts = [
    {
      id: 1,
      icon: chair,
      name: "The Dandy chair",
      price: "2349",
      tag: "furniture",
      designer: "Biggie",
      range: "1000 - 3000",
    },
    {
      id: 2,
      icon: vase,
      name: "Rustic Vase Set",
      price: "299",
      tag: "ceramic",
      designer: "Robert",
      range: "100 - 500",
    },
    {
      id: 3,
      icon: silky,
      name: "The Silky Vase",
      price: "499",
      tag: "ceramic",
      designer: "Biggie",
      range: "100 - 500",
    },
    {
      id: 4,
      icon: lamp,
      name: "The Lucy Lamp",
      price: "459",
      tag: "light",
      designer: "Liam",
      range: "100 - 500",
    },
    {
      id: 5,
      icon1: sofa,
      name: "The Popular suede sofa",
      price: "6499",
      tag: "furniture",
      designer: "Thom",
      range: "3000 - 5000",
    },
    {
      id: 6,
      icon: chair2,
      name: "The Dandy chair",
      price: "2999",
      tag: "furniture",
      designer: "Robert",
      range: "1000 - 3000",
    },
    {
      id: 7,
      icon: lamp1,
      name: "The Lucy Lamp",
      price: "400",
      tag: "light",
      designer: "Liam",
      range: "1000 - 3000",
    },
    {
      id: 8,
      icon: chairs,
      name: "3 set of chairs",
      price: "10000",
      tag: "furniture",
      designer: "Biggie",
      range: "5000+",
    },
    {
      id: 9,
      icon: cup,
      name: "White flowers vase",
      price: "600",
      tag: "cup",
      designer: "Thom",
      range: "500 - 1000",
    },
    {
      id: 10,
      icon: yellowChair,
      name: "Half chair",
      price: "2500",
      tag: "furniture",
      designer: "Robert",
      range: "1000 - 3000",
    },
    {
      id: 11,
      icon: blackChair,
      name: "Black chair",
      price: "3000",
      tag: "furniture",
      designer: "Robert",
      range: "1000 - 3000",
    },
    {
      id: 12,
      icon: pendant,
      name: "The pendant black light",
      price: "799",
      tag: "light",
      designer: "Liam",
      range: "500 - 1000",
    },
    {
      id: 13,
      icon1: BeigeSofa,
      name: "The leather Beige Sofa",
      price: "4899",
      tag: "furniture",
      designer: "Thom",
      range: "3000 - 5000",
    },
    {
      id: 14,
      icon: grayChair,
      name: "Comfort gray chair",
      price: "2799",
      tag: "furniture",
      designer: "Robert",
      range: "1000 - 3000",
    },
    {
      id: 15,
      icon: tableSet,
      name: "Pair of 3",
      price: "3999",
      tag: "furniture",
      designer: "Biggie",
      range: "3000 - 5000",
    },
    {
      id: 16,
      icon: whiteLight,
      name: "Study Light",
      price: "699",
      tag: "light",
      designer: "Thom",
      range: "500 - 1000",
    },
    {
      id: 17,
      icon: whiteMug,
      name: "The White Mug",
      price: "399",
      tag: "ceramic",
      designer: "Thom",
      range: "100 - 500",
    },
    {
      id: 18,
      icon: table,
      name: "The Wooden table",
      price: "499",
      tag: "furniture",
      designer: "Thom",
      range: "100 - 500",
    },
  ];